/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USlugRouteImport } from './routes/u/$slug'
import { Route as ToolsArtistAuditArtistIdRouteImport } from './routes/tools/artist-audit/$artistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsArtistAuditArtistIdRoute =
  ToolsArtistAuditArtistIdRouteImport.update({
    id: '/tools/artist-audit/$artistId',
    path: '/tools/artist-audit/$artistId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/$slug': typeof USlugRoute
  '/tools/artist-audit/$artistId': typeof ToolsArtistAuditArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u/$slug': typeof USlugRoute
  '/tools/artist-audit/$artistId': typeof ToolsArtistAuditArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/$slug': typeof USlugRoute
  '/tools/artist-audit/$artistId': typeof ToolsArtistAuditArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/u/$slug' | '/tools/artist-audit/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/u/$slug' | '/tools/artist-audit/$artistId'
  id: '__root__' | '/' | '/u/$slug' | '/tools/artist-audit/$artistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  USlugRoute: typeof USlugRoute
  ToolsArtistAuditArtistIdRoute: typeof ToolsArtistAuditArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/artist-audit/$artistId': {
      id: '/tools/artist-audit/$artistId'
      path: '/tools/artist-audit/$artistId'
      fullPath: '/tools/artist-audit/$artistId'
      preLoaderRoute: typeof ToolsArtistAuditArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  USlugRoute: USlugRoute,
  ToolsArtistAuditArtistIdRoute: ToolsArtistAuditArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
